<?php

namespace ZeplinBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfileRepository extends EntityRepository
{


    public function getProfilePicture(): array
    {

        $qb = $this->createQueryBuilder('p')
            ->select('img.image')
            ->innerJoin('ZeplinBundle:Images','img', 'WITH', 'img.id = p.imageId')
            ->getQuery();
        return $qb->execute();

    }


}
